---
# web front-end
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "fb-pdf-generator-api-{{ .Values.environmentName }}"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "fb-pdf-generator-api-{{ .Values.environmentName }}"
        appGroup: "fb-pdf-generator"
        fb-service-token-cache-access: "true"
        tier: "frontend"
    spec:
      serviceAccountName: "formbuilder-pdf-generator-{{ .Values.environmentName }}"
      containers:
        - name: "fb-pdf-generator-api-{{ .Values.environmentName }}"
          image: "754256621582.dkr.ecr.eu-west-2.amazonaws.com/formbuilder/fb-pdf-generator:{{ .Values.circleSha1 }}"
        securityContext:
          runAsUser: 1001
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        # non-secret env vars
        # defined in config_map.yaml
        envFrom:
          - configMapRef:
            name: fb-pdf-generator-api-env-{{ .Values.environmentName }}
        env:
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: fb-pdf-generator-api-secrets-{{ .Values.environmentName }}
                key: secret_key_base
          - name: SERVICE_TOKEN
            valueFrom:
              secretKeyRef:
                name: fb-platform-datastore-token-{{ .Values.environmentName }}
                key: token
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: fb-pdf-generator-api-secrets-{{ .Values.environmentName }}
                key: sentry_dsn
