apiVersion: v1
kind: Secret
metadata:
  name: fb-pdf-generator-api-secrets-{{ .Values.environment_name  }}
type: Opaque
data:
  secret_key_base: {{ .Values.secret_key_base }}
  sentry_dsn: {{ .Values.sentry_dsn }}
  metrics_access_key: {{ .Values.metrics_access_key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: fb-platform-pdf-generator-token-{{ .Values.environment_name }}
  namespace: formbuilder-platform-{{ .Values.environment_name }}
type: Opaque
data:
  token: {{ .Values.service_token }}
  metrics_access_key: {{ .Values.metrics_access_key }}
