kind: Service
apiVersion: v1
metadata:
  name: "fb-pdf-generator-api-svc-{{ .Values.environment_name }}"
  labels:
    app: "fb-pdf-generator-api-{{ .Values.environment_name }}"
    appGroup: "fb-pdf-generator"
spec:
  ports:
  - port: 80
    name: http
    targetPort: 3000
  selector:
    app: "fb-pdf-generator-api-{{ .Values.environment_name }}"
